export class AppConfig {
    DATE_FORMAT_SHORT_BE = 'YYYY-MM-DD';
}

export class ChartConfig {
    MAP_BACKGROUND_COLOR = '#EDECED';
    MAP_COUNTRY_COLOR = '#B0B0B0';
    MAP_COUNTRY_COLOR_LIGHT = '#EAB9BA';
    MAP_COUNTRY_COLOR_SELECTED = '#E19596';
    MAP_BUBBLE_COLOR = '#9A653A';

    CASES_CONFIRMED_COLOR = '#FCCE32';
    CASES_DEATHS_COLOR = '#D62D2D';
    CASES_RECOVERED_COLOR = '#5DA868';
    CASES_CONFIRMED_PER_CAPITA_COLOR = '#692CAA';
    CASES_DEATHS_PER_CAPITA_COLOR = '#692CAA';
}
